language: java
sudo: false
install: true

jdk:
  - oraclejdk7

addons:
  apt:
    packages:
    - mercurial 

script:
  - hg --version
  - ./travis.sh
                                                                                                                                                                 
cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "bCAnxqSxYujZcFSQZnhVLlaiPJv6mq6u+z/FPGWDRHmHG32/uHAeU+O/8aeZdWuQoSPskdxbIEcxjV7LO4UTKBr6Qolqqm+4EeCAE63p4ME6+N7BZzVcpCzHaRblcSPNmZA36jpNSyqb02atPi3hCHTow3vciJrJiiTG7xgMQ58="

